config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'facts#index'
  resources :facts do
    resources :comments
  end
  get 'about', to: 'facts#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :fact
end

app/models/fact.rb
class Fact < ApplicationRecord
  validates :title, presence: true, length: {maxiumum: 140, minimum: 3 }
  validates :blurb, presence: true, length: {maxiumum: 14000, minimum: 20 }
  validates :category, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :facts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @fact = Fact.find(params[:fact_id])
    @fact.comments.create(comment_params.merge(user: current_user))
    redirect_to fact_path(@fact)
  end

  def edit
    @comment = Comment.find(params[:id])
    #@fact.comments.create(comment_params.merge(user: current_user))
    if @comment.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params.to_h)
    redirect_to fact_path(@comment.fact)
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    @comment.destroy
    redirect_to fact_path(@comment.fact)
  end

  private

  def comment_params
    params.require(:comment).permit!
  end

end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    #facts.where(category: params[:category])
    @facts = if params[:category] == "coding"
      Fact.where(category: "coding")
    elsif params[:category] == "science"
      Fact.where(category: "science")
    elsif params[:category] == "other"
      Fact.where(category: "other")
    else
      @fact = Fact.all.order("created_at DESC").paginate(page: params[:page], per_page:5)
    end
    #@fact = Fact.order("RANDOM()").first
  end

  def new
    @fact = Fact.new
  end

  def create
    #@fact = Fact.new(params)
      #if @object.save
      #  redir
      #else
      #render new (
    @fact = current_user.facts.create(fact_params)

    hash = DictionaryService.new
    escaped_title = URI.escape(@fact.title)
    @fact.definition = hash.def_from_api(escaped_title)
    @fact.save

    if @fact.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def about
  end

  def show
    @fact = Fact.find_by_id(params[:id])
    @comment = Comment.new
    if @fact.blank?
      render plain: 'Not Found :(', status: :not_found
    end
  end

  def edit
    @fact = Fact.find(params[:id])
    if @fact.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @fact = Fact.find(params[:id])
    if @fact.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    @fact.update_attributes(fact_params)
    redirect_to root_path
  end

  def destroy
    @fact = Fact.find(params[:id])
    if @fact.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    @fact.destroy
    redirect_to root_path
  end


  private

  def fact_params
    params.require(:fact).permit(:title, :blurb, :category, :definition)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/comments/edit.html.erb
<%= simple_form_for @comment, url: fact_comment_path, :method => :patch do |f| %>
  <%= f.input :message %>
  <%= f.submit "Edit Comment", class: 'btn btn-primary' %>
<% end %>

app/views/facts/about.html.erb
<div class="col-10 offset-1">
  <h1>About the Feynmanizer</h1>
  <h2>What is the Feynman Technique?</h2>
  <p>The Feynman Technique is a mental model named after Richard Feynman, a physisict
  who won a Nobel Prize for his work in Quantum Electrodynamics.</p>
  <h4>Four Steps:</h4>
  <ol>
  <li>Choose a concept.</li>
  <li>Teach a toddler.</li>
  <li>Identify gaps.</li>
  <li>Review & simplify.</li> 
  </ol>
</div>

app/views/facts/edit.html.erb
<div class="form">
<h1>Refactor your Entry.</h1>
<br>
<%= simple_form_for @fact do |f| %>
  <%= f.input :title, label: 'What\'s the concept?', readonly: true %>
  <br>
  <%= f.input :blurb, label: 'How would you explain it to a child?'%>
  <br>
  <%= f.input :category, as: :radio_buttons, collection: [['coding', 'Coding'], ['science', 'Science'], ['other', 'Other']], label_method: :second, value_method: :first %>
  <br>
  <%= f.submit 'Update', class: 'btn btn-info' %>

<% end %>
</div>
<br>
<br>

app/views/facts/index.html.erb
<% @facts.each do |fact| %>
<div class="card">
<h1><%= link_to fact.title, fact_path(fact) %></h1>
<h2><%= fact.blurb %></h2>
<p><%= fact.category %></p>
<br>
<% if fact.user.present? %>
<small><%= fact.user.email %></small>
<% end %>
</div>

<% end %>

app/views/facts/new.html.erb
<div class="form">
<h1>Pour your knowledge.</h1>
<br>
<%= simple_form_for @fact do |f| %>
  <%= f.input :title, label: 'What\'s the concept?' %>
  <br>
  <%= f.input :blurb, label: 'How would you explain it to a child?'%>
  <br>

  <%= f.input :category, as: :radio_buttons, collection: [['coding', 'Coding'], ['science', 'Science'], ['other', 'Other']], label_method: :second, value_method: :first %>
  <%= f.submit 'Create', class: 'btn btn-info' %>

<% end %>
</div>
<br>
<br>

app/views/facts/show.html.erb
<h1 class="text-center"><%= @fact.title %></h1>
<br>
<h3 class="text-center"><%= @fact.definition %></h3>
<h2><%= @fact.blurb %></h2>
<p><%= @fact.category %></p>
<div class="float-right">
<% if current_user && current_user == @fact.user %>
  <%= link_to 'Edit', edit_fact_path(@fact), class: 'btn btn-warning' %>
  <%= link_to 'Destroy', fact_path(@fact), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
<% end %>
</div>
<div class="clear"></div>
<%= simple_form_for @comment, url: fact_comments_path(@fact) do |f| %>
  <%= f.input :message %>
  <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
<% end %>
<br>
<h1>Comments</h1>

<% @fact.comments.each do |comment| %>
  <div>
    <blockquote>
      <b><%= comment.message %></b>
      <small><%= comment.user.email %></small>
      <div class="float-right">
      <% if current_user && current_user == comment.user %>
        <%= link_to 'Edit', edit_fact_comment_path(@fact, comment), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', fact_comment_path(@fact, comment), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
      <% end %>
      </div>

    </blockquote>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feynmanizer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class='row top'>
      <div class='col-2'>
        <%= link_to image_tag("feynman.png",  alt: "Feynman", class: "feynman-img"), root_path %>
      </div>
      <div class="col-4 tagline">
        Complex concepts boiled down with the Feynman technique.
      </div>
      <div class="col-6 links">

          <%= link_to 'Contribute', new_fact_path, class: 'no-drop' %>
          <%= link_to 'About', about_path , class: 'no-drop' %>

        <div class="dropdown">
          <button class="dropbtn">Categories</button>
          <div class="col-3 dropdown-content">
            <%= link_to 'Coding', facts_path({category:"coding"}) %>
            <%= link_to 'Science', facts_path({category:"science"}) %>
            <%= link_to 'Other', facts_path({category:"other"}) %>
          </div>
        </div>
            <% if user_signed_in? %>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'no-drop' %>
            <% else %>
              <%= link_to 'Sign in', user_session_path, class: 'no-drop' %>
              <%= link_to 'Sign Up', new_user_registration_path, class: 'no-drop' %>
            <% end %>
      </div>
    </header>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <br class='clear'>
    <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>
<br>
<br>
    <div class="footer">
      <div class="container">
        <div class="row">

          <div class="col-12 footer-blurb">
            Proudly hacked by <a href="https://arieloring.netlify.com/">Arielle Loring.</a><br />
          </div>

        </div>

      </div>

    </div>


    <% yield %>
  </body>
</html>